CREATE TABLE ACCOUNT_TRANSACTIONS(
ID INT PRIMARY KEY,
ACCOUNT_NUMBER NUMBER(5),
TRANSACTION_AMOUNT NUMBER(30,5),
TRANSACTION_TYPE VARCHAR(10),
CREATED_BY VARCHAR(50),
CREATED_DATE DATE
);

CREATE TABLE ACCOUNT_DETAILS(
ID INT PRIMARY KEY,
ACCOUNT_NUMBER NUMBER(5),
BALANCE NUMBER(30,5),
CREATED_BY VARCHAR(50),
CREATED_DATE DATE,
UPDATED_BY VARCHAR(50),
UPDATED_DATE DATE
);